import { getCloudflareContext } from '@opennextjs/cloudflare'

// Kept in sync with routing.ts's locale list, minus 'en' (the fallback default).
const SUPPORTED_LOCALES = ['fr', 'es', 'de', 'ru', 'zh', 'zh-TW', 'it', 'nl'] as const

export function normalizeLocale(locale: string): string {
  return (SUPPORTED_LOCALES as readonly string[]).includes(locale) ? locale : 'en'
}

const cache = new Map<string, unknown>()

async function readFromDisk<T>(path: string): Promise<T> {
  const { readFile } = await import('node:fs/promises')
  const { join } = await import('node:path')
  const raw = await readFile(join(process.cwd(), 'public', 'locale-data', path), 'utf-8')
  return JSON.parse(raw) as T
}

async function readFromAssets<T>(path: string): Promise<T> {
  const { env } = await getCloudflareContext({ async: true })
  if (!env.ASSETS) {
    throw new Error(`No ASSETS binding available to load locale data: ${path}`)
  }
  const res = await env.ASSETS.fetch(new URL(`https://assets.internal/locale-data/${path}`))
  if (!res.ok) {
    throw new Error(`Failed to load locale data "${path}": ${res.status}`)
  }
  return (await res.json()) as T
}

/**
 * Loads a per-locale JSON data file (generated by scripts/generate-locale-data.ts
 * into public/locale-data/) instead of statically importing every locale's source
 * module — which previously bundled all 7 locales' content into every route,
 * pushing the Worker script well past Cloudflare's size limit.
 *
 * `next build` renders every page once (even ones that end up marked dynamic)
 * to decide whether it can be statically optimized. That happens hundreds of
 * times across 7 parallel build workers, entirely in plain Node.js — spinning
 * up a local Cloudflare context/proxy per call there is both very slow and,
 * under that much parallelism, reliably crashes on Windows. Reading the
 * already-generated JSON straight off disk during the build sidesteps that
 * entirely; the ASSETS-binding path is only used at real request time
 * (`next dev`, `wrangler dev`/preview, and the deployed Worker).
 */
export async function fetchLocaleData<T>(path: string): Promise<T> {
  const cached = cache.get(path)
  if (cached !== undefined) return cached as T

  const data = process.env.NEXT_PHASE === 'phase-production-build'
    ? await readFromDisk<T>(path)
    : await readFromAssets<T>(path)

  cache.set(path, data)
  return data
}
